# Generated by Django 4.0.1 on 2022-01-27 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_film2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film2',
            new_name='Anime',
        ),
    ]
