# Generated by Django 4.0.1 on 2022-01-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_expertrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertrecommendation',
            name='activity',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertrecommendation',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertrecommendation',
            name='information',
            field=models.TextField(null=True),
        ),
    ]
