# Generated by Django 4.0.1 on 2022-01-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_expertrecommendation_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expertrecommendation',
            name='author',
        ),
        migrations.AlterField(
            model_name='expertrecommendation',
            name='information',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
