# Generated by Django 4.0.1 on 2022-01-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_expertrecommendation_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expertrecommendation',
            old_name='book',
            new_name='books',
        ),
    ]
